services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - store_data:/app/data/db
      - ./Brigade_Bangalore_10_April_26.csv:/app/Brigade_Bangalore_10_April_26.csv:ro
    environment:
      - STORE_ID=STORE_BLR_002
      - DATABASE_URL=sqlite:////app/data/db/store_intelligence.db
      - ENV=production
    restart: unless-stopped

volumes:
  store_data:
